### ISSUE TITLE
XLR8DMemTest does not work correctly on Sno

### ISSUE THREAD

**Issue by PaulZC** [AloriumTechnology/XLR8DMem#1]
Hi there,

I'm using my Sno board for the first time and am getting strange results with the XLR8DMemTest example. The XLR8DMem.write - or possibly the .read - appears to be failing?

Here's the output from the Serial Monitor:
```
Starting Value: Overwrite!
Ending Value: 
Finished
```

I added the extra ```Serial.println("Finished");``` just to make sure the code was getting all the way to the end. Here's the full code:
```
#include <XLR8DMem.h>

uint16_t address = 30;
char * string = "Hello DMem";
char * returned = "Overwrite!";

void setup() {
  Serial.begin(115200);
  Serial.print("Starting Value: ");
  Serial.println(returned);
  XLR8DMem.write(address, string, strlen(string));
  XLR8DMem.read(address, returned, strlen(string));
  Serial.print("Ending Value: ");
  Serial.println(returned);
  Serial.println("Finished");
}

void loop() {}
```

Like I say, I'm just getting started with this board so it's entirely possible I'm doing something dumb, or haven't configured the board correctly.
I'm using Arduino 1.8.12 on 64-bit Windows. I've downloaded the latest boards and libraries following the instructions in the quick start guide. I'm connecting via a 3.3V FTDI cable.
Thanks in advance!
Paul

**Comment by PaulZC** [comment]
I don't know if this is related, but I see some failures when I run the XLR8SelfTest example:
```
***************
FPGA Image: 16 MHz Float Servo NeoPixel  1.0.2753
***************
XLR8 Hardware Version Number = 2753
XLR8 CID = 0xACE0EE10
DesignConfig = 0x428
Image = 1
Clock = 16 MHz
XB_ENABLE = 0xF
Has Floating Point Add, Subtract, and Multiply
Has Floating Point Divide
Has Servo XB
Has NeoPixel XB
Int Osc = 83.88 MHz
5V supply =~ 0.09V  assumed to be USB power
******* TEST RESULTS **********
88 tests run
68 tests pass
20 tests fail
  Last failure at test number 61
********** FAIL ***************
```

I have just updated the FPGA image - successfully - to:

![image](https://user-images.githubusercontent.com/5690545/87223907-adf18580-c378-11ea-99b4-55c98900b7d3.png)

**Comment by jpecor** [comment]
Hi Paul - 

There are a group of tests that assume there are some loopback paths wired up externally to the board, and they can generate failures. It's really something that we need to fix in the test itself, because we have had a few people run across the same thing you are seeing.

I'll make sure that they are the failures we are expecting if the board isn't wired up to test those loopback and ADC paths.  

Regarding XLR8DemTest, the XLR8DMem functionality is only supported on our Hinj board.  I apologize for the confusion.  I know that the name is misleading.  

At a minimum, notes in the comment header for Hinj-only examples/tests might help.  I'll add that to our action items.

I hope this helps.  

Thanks!
Jason

**Comment by PaulZC** [comment]
Thank you Jason - that clears that up.
Thanks for the prompt response - on a Saturday too!
All the best,
Paul

**Comment by jpecor** [comment]
My pleasure!  Let me know if there's any other help you need.
